using System;
namespace Roulette
{
    /// <summary>
    /// Roulette class generates number and color after the spin.
    /// </summary>
    public class Roulette
    {
        /// <summary>
        /// The random is used for generating number.
        /// </summary>
        Random random;

        /// <summary>
        /// Specified number event handler.
        /// </summary>
        public delegate void SpecNumEventHandler(object sender,RouletteSpinEventArgs e);

        /// <summary>
        /// Specified color event handler.
        /// </summary>
        public delegate void SpecColEventHandler(object sender, RouletteSpinEventArgs e);

        public event SpecNumEventHandler OnSpecNumber;
        public event SpecColEventHandler OnSpecColor;

        /// <summary>
        /// The color depends on the number, color is set in SetColor() method. If the number is even - the color is red, otherwise the color is black, in case of the number = 0 - the color is green.
        /// </summary>
        Colors color;

        /// <summary>
        /// The number is generated by random.
        /// </summary>
        int number;

        /// <summary>
        /// Initializes a new instance of the Roulette class.
        /// </summary>
        public Roulette()
        {
            random = new Random();
        }

        /// <summary>
        /// Spins the roulette and getting the new number and color.
        /// </summary>
        public void SpinRoulette()
        {
            number = random.Next(0, 37);//0 is lower bound and 36 is higher bound.
            SetColor();
            OnNewSpin(this, new RouletteSpinEventArgs(number, color));//Raises events.
        }

        protected virtual void OnNewSpin(object sender, RouletteSpinEventArgs e)
        {
            OnNewSpecifiedCol(this, new RouletteSpinEventArgs(number, color));
            OnNewSpecifiedNumber(this, new RouletteSpinEventArgs(number, color));
        }

        protected virtual void OnNewSpecifiedNumber(object sender,RouletteSpinEventArgs e)
        {
            OnSpecNumber?.Invoke(sender,e);
        }

        protected virtual void OnNewSpecifiedCol(object sender, RouletteSpinEventArgs e)
        {
            OnSpecColor?.Invoke(sender, e);
        }

        /// <summary>
        /// Sets the color.
        /// </summary>
        void SetColor()
        {
            int temp = number;
            if (temp == 0)
            {
                color = Colors.Green;
                return;
            }
            temp = number % 2;
            switch (temp)
            {
                case 1:
                    {
                        color = Colors.Red;
                        break;
                    }
                case 0:
                    {
                        color = Colors.Black;
                        break;
                    }
                default:
                    {
                        color = Colors.Undefined;
                        break;
                    }
            }
        }

        /// <summary>
        /// Log this instance to console.
        /// </summary>
        void Log()
        {
            Console.WriteLine(number + " " + color);
        }
    }
}
